require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - bin/**/*
    - db/schema.rb
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
